[package]
name = "gitstats"
version = "0.1.0"
edition = "2021"


[dependencies]
git2 = "0.19.0"
eframe = "0.29.1"
plotters = "0.3"
egui_extras = "0.29.1"
log = "0.4"
chrono = "0.4"
image = "0.25.5"
tokio = { version = "1", features = ["full"] }
